from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
INSTANCES_DIR = DATA_DIR / "instances"
WITH_CHANGEOVER_INSTANCES_DIR = INSTANCES_DIR / "in"
WITHOUT_CHANGEOVER_INSTANCES_DIR = INSTANCES_DIR / "out"
GENERATED_INSTANCES_DIR = INSTANCES_DIR / "generated"
SOLUTIONS_DIR = DATA_DIR / "solutions"
LP1_SOLUTIONS_DIR = SOLUTIONS_DIR / "lp1"
LP2_SOLUTIONS_DIR = SOLUTIONS_DIR / "lp2"
WITH_CHANGEOVER_SOLUTIONS_DIR = LP1_SOLUTIONS_DIR / "in"
WITHOUT_CHANGEOVER_SOLUTIONS_DIR = LP1_SOLUTIONS_DIR / "out"
REEVALUATED_CHANGEOVER_SOLUTIONS_DIR = WITHOUT_CHANGEOVER_SOLUTIONS_DIR / "recomputed"
RESULTS_DIR = PROJECT_ROOT / "results"
