from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"

INSTANCES_DIR = DATA_DIR / "instances"
CHANGEOVER_INSTANCES_DIR = INSTANCES_DIR / "in"
ZERO_CHANGEOVER_INSTANCES_DIR = INSTANCES_DIR / "out"
GENERATED_INSTANCES_DIR = INSTANCES_DIR / "generated"

SOLUTIONS_DIR = DATA_DIR / "solutions"
MILP_SOLUTIONS_DIR = SOLUTIONS_DIR / "milp"
CHANGEOVER_SOLUTIONS_DIR = MILP_SOLUTIONS_DIR / "in"
ZERO_CHANGEOVER_SOLUTIONS_DIR = MILP_SOLUTIONS_DIR / "out"
REPRICED_SOLUTIONS_DIR = ZERO_CHANGEOVER_SOLUTIONS_DIR / "recomputed"

RESULTS_DIR = PROJECT_ROOT / "results"
